FROM jrepp/base
MAINTAINER Jacob Repp <jacobrepp@gmail.com>

RUN apt-get install -y \
    binutils-gold \
    ccache \
    clang \
    cmake \
    distcc \
    git \
    make \
    vim \
    wget

ENTRYPOINT ["/bin/bash"]
